#!/usr/bin/env bash
# A script to install and configure Nginx on web01 server

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee -a /var/www/html/index.html
sudo service nginx restart
